### ISSUE TITLE
Support Blackberry Cascades

### ISSUE THREAD

**Issue by heri16** [cyndis/qmlrs#3]
Since Blackberry is a major contributor to the QtQuick project, ever thought about making this work on BlackBerry QNX + Qt?

**Comment by florianjacob** [comment]
@heri16 I don't have any QNX devices so I can't test this, but there should be no fundamental problems if rust compiles to it and there's a version of Qt5 available that's new enough, at least Qt5.2.

Please reopen as soon as you have any specific problems with qmlrs that we can try to solve.
