### ISSUE TITLE
Is the project alive ?

### ISSUE THREAD

**Issue by alexjp** [cyndis/qmlrs#30]
Hi,

Sorry for asking this, but is this project still alive ?

It is a very interesting project !!!

Thanks !

**Comment by florianjacob** [comment]
As alive as the sum of the willingness of all of us to contribute to it. :wink:
I don't know how far I'll get with big issues like #22, though, but I'll give it a try after I finished the low-hangig fruits to get familiar with the project and code. You're welcome to help out, of course. :smile:

**Comment by alexjp** [comment]
well.... I am very much a newbie in rust, but I sure would love to help out.

**Comment by florianjacob** [comment]
We all have to start somewhere. :smiley: Testing and using qmlrs also helps, I think there are only a very small number of projects out there which actually use qmlrs.
