### ISSUE TITLE
Finish (Travis) CI integration

### ISSUE THREAD

**Issue by florianjacob** [cyndis/qmlrs#32]
It would be really nice to have a CI integration that at least builds the library and the examples.
There already exists https://travis-ci.org/cyndis/qmlrs/ from a year ago - maybe it can be brought to live with stable rust?

**Comment by cyndis** [comment]
It might be possible if travis has updated their Ubuntu version since - when I tried to add CI integration then it was pretty much impossible to install a new enough version of Qt.

**Comment by florianjacob** [comment]
I [did some experiments](https://github.com/florianjacob/qmlrs) and got the basic build running on Ubuntu 14.04.

I'm [stuck with the test cases, though](https://travis-ci.org/florianjacob/qmlrs/builds/106306229). I added some dummy println!s to see whether the execution stalls before the exec() stall, but that's not the case. So for some reason, the quit() signal is not triggered. :cry:

Any idea what could go wrong there? Maybe related to the build servers running headless?

**Comment by cyndis** [comment]
Could be, even though Qt5Gui shouldn't be invoked at all with a headless engine. Still, there might be some dependency. Could also be a change or bugfix between Qt 5.2 and 5.5. You could try changing the interval to something greater than zero or adding prints, checking if you can print a debug message from onComponentCompleted for example.

**Comment by florianjacob** [comment]
You were exactly right with the zero interval for the timer, that was the problem! :+1:
See #33  for the results. The badge is already for /cyndis/qmlrs repo, therefore it currently shows build error, but I already tested it for my fork. Only thing left would be to enable travis for your repo again.

**Comment by cyndis** [comment]
Nice :) I just enabled the repo on travis, but I don't know if I can actually kick off a build for the latest commit (without making a new one). Still, we can probably consider this issue done.

**Comment by florianjacob** [comment]
For you as repo owner, there should be a restart circle-arrowish button at the top right of the colored boxes describing the build status. :smile:

**Comment by cyndis** [comment]
Yeah, there is one and I tried it, but looks like it will only retry the old run I tried a year ago.. :)

**Comment by florianjacob** [comment]
Oh, that's very helpful, indeed. xD Well, but everything *should* be ready for the next PRs / commits now. :)

**Comment by florianjacob** [comment]
Found a trivial change to do, and hurray, everything works!
Thanks for Collaborator status! :D
