### ISSUE TITLE
QCustomPlot using qmlrs

### ISSUE THREAD

**Issue by Felix99** [cyndis/qmlrs#50]
Hi all,

Is there any way to include QCustomPlot with qmlrs into rust? 
It can be found at http://www.qcustomplot.com .
Any help would be appreciated!

Thanks
Felix

**Comment by florianjacob** [comment]
QCustomPlot seems to be a QWidget library. qmlrs and all similar language binding libraries only support QML libraries. So no, it won't work, you'd need some kind of C++ QML wrapper around QCustomPlot or another plotting library that exposes a QML interface directly.

Sorry! :worried:

**Comment by Felix99** [comment]
OK, thank you for your comment anyway.
