### ISSUE TITLE
White-Oak/qml-rust

### ISSUE THREAD

**Issue by nerdoc** [cyndis/qmlrs#52]
Is there any relation to [White-Oak/qml-rust](https://github.com/White-Oak/qml-rust)? is this a parallel project with the same aims? Wouldn't it be good to join your forces?
I'd love to see good,stable Qt5/QML bindings for Rust - but developing 2 different in parallel is a bit much of a needless effort?

Don't get me wrong, this is just a qustion.

**Comment by White-Oak** [comment]
@nerdoc as you can see, this one (`qmlrs`) is no longer actively mantained.

`qml-rust` is more advanced, it supports qt objects bindings (so things like slots and signals are possible).
It is also based on different bindings.

I am (the author of `qml-rust`) in no relation to this project, or to its author.

**Comment by ShalokShalom** [comment]
@White-Oak 

>  it supports qt objects bindings (so things like slots and signals are possible)

Does this mean that your goal is full qt support?

**Comment by nerdoc** [comment]
Thanks.
