### ISSUE TITLE
how to support  import QtQuick.XmlListModel 2.0

### ISSUE THREAD

**Issue by dallyshalla** [cyndis/qmlrs#9]
Greetings, thanks 10000 times for this library:

I am wondering about this: 
import QtQuick.XmlListModel 2.0

error:
module "QtQuick.XmlListModel" is not installed

**Comment by cyndis** [comment]
Hi, all Qml-side imports just go through Qt's normal loading, so make sure that you have a new enough Qt with the QtQuick.XmlListModel module installed. Qmlrs doesn't modify the load paths or anything.

**Comment by Liamsi** [comment]
`import QtQuick.XmlListModel 2.0`  works for me  in Qt 5.4.1

**Comment by florianjacob** [comment]
@dallyshalla: I'm closing this, as it works for @Liamsi it's highly unlikely this is an actual problem with qmlrs, but probably a missing Qt module or old version of Qt. Please reopen if you still have problems.
